Course Details Page Formatted
sudouc/a117_mobile pull request #27
Opened 2017-04-01 09:18 UTC by robodair

Closes #6

2017-04-01 23:55 UTC, Jonno1809 requested changes
Due to API endpoints changes, ApiEndpoints.COURSE + '/' + AppConstants.ALL in courses-provider.ts will have to be changed to ApiEndpoints.COURSE

2017-04-02 00:19 UTC, robodair commented
@Jonno1809 that will be fixed in a PR for #30

2017-04-02 00:20 UTC, Jonno1809 approved these changes

2017-04-02 00:20 UTC, Jonno1809 commented
No worries.

2017-04-02 00:22 UTC, merged